---
title: "Wajid Iqbal"
format: 
  html:
    toc: false
    css: styles.css
---

Street# Unknown Road, City, country

Email: [wwajidiqbal@gmail.com](mailto:wwajidiqbal@gmail.com) | Phone: 0121234567

[GitHub](https://github.com/Wajidiqbal1) | [Google Scholar](https://scholar.google.com/citations?user=WQk1k7wAAAAJ&hl=en) | [LinkedIn](https://www.linkedin.com/in/wajid-iqbal-a5b533186/)

---

## Personal Statement

Mr. ABC expertise lies in the genetics and molecular biology and statistics and data science and so on.

---

## Positions and Employment

### Research Assistant

**Dept: statistical genetics, FOS, university** \| city Islamabad, Pakistan \| 2021 - 2023

-   Analyzed exome sequencing data from families.
-   developed a package that does this and this.
-   Developed user-friendly bioinformatics pipelines and streamlined workflows for exome and transcriptome analysis.

### Data Analysis

**ABC Laboratories** \| WIH Karachi \| July 1950 - Dec 2023

-   Contributed knowledge of statistics in interpreting the variants.

---

## Education

### MS 

**ABC University** \| Islamabad, Pakistan \| 2023

### BS Biotechnology

**Royal college london** \| London, UK \| 2021

### HSSC

**QIMS** \| bamkhel,  \| 2016

### SSC

**KIPS** \| Bamkhel \| 2014

---

## Skills

-   **Laboratory**: Genotyping, ABC, CDE
-   **Bioinformatics**: R language, Python, MATLAB
-   **Languages**: Fluent: English;

---

## Certificates, Courses, and Invited Lectures/Seminars

-   2023 Interpreting Genomic Variation: Fundamental Principles St George's, University of London
-   2023 Genomics in the NHS: A Clinician's Guide to Genomic Testing for Rare Disease Health Education England
-   2023 NGS Data Analysis COMSATS, 
-   2023 Personalized Medicine in Pakistan: Future or Fiction (PF2), Biologia360®
-   2023 Presenter in NGS data analysis workshop

---

## Publications
-   M. Saleem Faisal, Imran Hussain, M. Abdullah Ikram, Syed Babr Shah, Abdul Rahman, **Wajid Iqbal**. Journal of Chemotherapy: Irinotecan dosing and pharmacogenomics: a comprehensive exploration based on UGT1A1 variants and emerging insights. JOC3668R1
---

## References

-   will be provide upon request.
